---
title: "Calculating win-loss statistics using summary data"
subtitle: "Reconstruction based on published Kaplan-Meier curves of overall and event-free survival"
date: today
---

**WinKM** provides a simple way to calculate win-loss statistics using summary data. 
This is useful when you have access to published Kaplan-Meier (KM) curves of *overall survival* (OS) and nonfatal *event-free survival time* (EFS), but not the individual patient data,
as is often the case in **systematic reviews** and **meta-analyses**.

## Basic idea

The basic idea is to consider the win and loss proportions by a certain time as a functional
of the joint distribution of OS and EFS. 
Since we only have the marginal distributions through the KM curves, we will need to
infer their associations via additional summary data like *total event counts and rates*.

All in all, we need the following for each arm:

-   **KM estimates** for OS and EFS (obtained by scanning and digitizing the curves using free online tools like [WebPlotDigitizer](https://apps.automeris.io/wpd/);
-   **At-risk table** at selected time points (usually provided below the KM curves);
-   **Total event counts** (reported in the CONSORT diagram or results section):
    -   Deaths (OS);
    -   EFS endpoints (first of death/nonfatal event);
    -   Nonfatal event.

## Example

